plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/lease-emp-mac-masateru-ozeki/Documents/尾関/assignflow/deploy"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]